"""followers table added

Revision ID: 438cd88ad33f
Revises: 88eed17d776a
Create Date: 2020-03-25 23:48:54.632419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438cd88ad33f'
down_revision = '88eed17d776a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
